### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by jokari4242** [netinfluence/NetinfluenceUploadBundle#2]
Hi !

Thanks for this nice bundle. I'm trying to install but, i don't understand how storing path in a collection (ManyToMany?), what kind of relation i need in my objet.

Could you help me please?

Thanks :-)

Antoine

**Comment by jokari4242** [comment]
I have this error :

```
Cannot read index "0" from object of type "AM\ClassifiedAdsBundle\Entity\MyFile" because it doesn't implement \ArrayAccess.
```

**Comment by romaricdrigon** [comment]
You are using a `netinfluence_upload_image_collection`, right?  

OK let's comment the example:

``` php
        $form = $this->createFormBuilder()
            ->add('photos', 'netinfluence_upload_image_collection', array(
                'max_files' => 3,
                'options'   => array(
                    'data_class' => 'Netinfluence\DemoBundle\Entity\MyFile'
                )
            ))
            ->getForm()
        ;
```

`photos` will be an array of `Netinfluence\DemoBundle\Entity\MyFile`. To speak in Doctrine entity words, `photos` should be a *ToMany relation to `Netinfluence\DemoBundle\Entity\MyFile`.

**Comment by jokari4242** [comment]
Ok thanks, it's work perfectly ;-) !
